# Conda environment
name: scheme_env
channels:
  - conda-forge
  - r
  - defaults
dependencies:
  # Install basic R environment for benchmarking
  - r-base=4.1.*
  - r-tidyverse
  - r-devtools
  - r-rlang
  - r-docopt
  - r-littler
  - r-biocmanager
  # Dependencies for the code itself
  - python=3.9.*
  - pip
  - jax=0.3.*
  - numpyro=0.10.*
  - tqdm=4.64.*
  - networkx=2.8.*
  - scanpy=1.9.*
  - pip:
      - treeo~=0.2.1
      - louvain~=0.8.0
      - leidenalg~=0.9.0